In [1]:
from google.colab import files
uploaded = files.upload()

Saving ecommerce_return_abuse_dataset.csv to ecommerce_return_abuse_dataset.csv

In [2]:
import pandas as pd

df = pd.read_csv("ecommerce_return_abuse_dataset.csv")
df.shape

(60000, 35)

In [3]:
df.head()

,order_id,customer_id,age,account_age_days,customer_segment,country,platform,device_type,payment_method,product_category,...,shipping_carrier,address_change_before_delivery,refund_to_different_account,multiple_accounts_flag,customer_support_contacts,previous_dispute_count,wishlist_to_cart_time_hrs,review_left_after_return,abuse_type,abuse_label
0,ORD2024554,CUST408891,68,1473,New,US,Web Browser,iPhone,Crypto,Toys,...,OnTrac,0,0,0,1,0,70.5,0,Legitimate,0
1,ORD2019797,CUST898762,64,1211,Silver,FR,Tablet App,MacBook,PayPal,Books,...,FedEx,0,0,0,0,0,25.3,0,Legitimate,0
2,ORD2058733,CUST906263,52,1291,Bronze,US,Web Browser,iPad,Crypto,Clothing,...,FedEx,1,0,0,0,0,36.6,0,Legitimate,0
3,ORD2015301,CUST601672,63,1743,Bronze,CA,Web Browser,iPhone,PayPal,Home & Kitchen,...,USPS,1,0,0,3,0,4.4,1,Fraudulent Return,2
4,ORD2014206,CUST316429,21,2478,Gold,US,Web Browser,Windows PC,Debit Card,Clothing,...,OnTrac,0,0,0,1,1,40.9,0,Legitimate,0

In [4]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 35 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   order_id                        60000 non-null  object
 1   customer_id                     60000 non-null  object
 2   age                             60000 non-null  int64
 3   account_age_days                60000 non-null  int64
 4   customer_segment                60000 non-null  object
 5   country                         60000 non-null  object
 6   platform                        60000 non-null  object
 7   device_type                     60000 non-null  object
 8   payment_method                  60000 non-null  object
 9   product_category                60000 non-null  object
 10  avg_order_value_usd             60000 non-null  float64
 11  refund_amount_requested_usd     60000 non-null  float64
 12  is_high_value_item              60000 non-null  int64
 13  discount_used                   60000 non-null  int64
 14  order_date                      60000 non-null  object
 15  return_date                     60000 non-null  object
 16  days_to_return                  60000 non-null  int64
 17  return_reason                   60000 non-null  object
 18  total_orders_lifetime           60000 non-null  int64
 19  total_returns_lifetime          60000 non-null  int64
 20  return_rate_pct                 60000 non-null  float64
 21  item_returned_opened            60000 non-null  int64
 22  return_packaging_intact         60000 non-null  int64
 23  photo_evidence_provided         60000 non-null  int64
 24  tracking_number_valid           60000 non-null  int64
 25  shipping_carrier                60000 non-null  object
 26  address_change_before_delivery  60000 non-null  int64
 27  refund_to_different_account     60000 non-null  int64
 28  multiple_accounts_flag          60000 non-null  int64
 29  customer_support_contacts       60000 non-null  int64
 30  previous_dispute_count          60000 non-null  int64
 31  wishlist_to_cart_time_hrs       60000 non-null  float64
 32  review_left_after_return        60000 non-null  int64
 33  abuse_type                      60000 non-null  object
 34  abuse_label                     60000 non-null  int64
dtypes: float64(4), int64(18), object(13)
memory usage: 16.0+ MB

order_id                          0
customer_id                       0
age                               0
account_age_days                  0
customer_segment                  0
country                           0
platform                          0
device_type                       0
payment_method                    0
product_category                  0
avg_order_value_usd               0
refund_amount_requested_usd       0
is_high_value_item                0
discount_used                     0
order_date                        0
return_date                       0
days_to_return                    0
return_reason                     0
total_orders_lifetime             0
total_returns_lifetime            0
return_rate_pct                   0
item_returned_opened              0
return_packaging_intact           0
photo_evidence_provided           0
tracking_number_valid             0
shipping_carrier                  0
address_change_before_delivery    0
refund_to_different_account       0
multiple_accounts_flag            0
customer_support_contacts         0
previous_dispute_count            0
wishlist_to_cart_time_hrs         0
review_left_after_return          0
abuse_type                        0
abuse_label                       0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df['abuse_type'].value_counts()

abuse_type
Legitimate           42060
Policy Abuser         7192
Fraudulent Return     6112
Wardrobing            4636
Name: count, dtype: int64

In [7]:
df.describe()

,age,account_age_days,avg_order_value_usd,refund_amount_requested_usd,is_high_value_item,discount_used,days_to_return,total_orders_lifetime,total_returns_lifetime,return_rate_pct,...,photo_evidence_provided,tracking_number_valid,address_change_before_delivery,refund_to_different_account,multiple_accounts_flag,customer_support_contacts,previous_dispute_count,wishlist_to_cart_time_hrs,review_left_after_return,abuse_label
count,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,...,60000.000000,60000.00000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.00000
mean,44.105383,1250.687700,188.987098,176.197371,0.379300,0.238650,16.087550,41.304550,8.943850,19.073007,...,0.379417,0.92850,0.093450,0.040867,0.078350,1.392000,1.098050,30.168445,0.249917,0.55540
std,15.258403,722.018931,137.797571,136.587287,0.485217,0.426262,11.395042,25.198816,15.000508,22.730017,...,0.485246,0.25766,0.291064,0.197983,0.268724,1.705995,1.375367,22.863372,0.432968,0.95618
min,18.000000,1.000000,15.000000,12.120000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,0.000000,0.00000
25%,31.000000,626.000000,92.850000,84.410000,0.000000,0.000000,6.000000,20.000000,1.000000,2.700000,...,0.000000,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,6.200000,0.000000,0.00000
50%,44.000000,1251.000000,165.115000,150.510000,0.000000,0.000000,15.000000,39.000000,3.000000,8.800000,...,0.000000,1.00000,0.000000,0.000000,0.000000,1.000000,1.000000,28.400000,0.000000,0.00000
75%,57.000000,1875.000000,247.672500,224.025000,1.000000,0.000000,24.000000,60.000000,9.000000,35.500000,...,1.000000,1.00000,0.000000,0.000000,0.000000,1.000000,1.000000,50.400000,0.000000,1.00000
max,70.000000,2500.000000,799.960000,836.680000,1.000000,1.000000,55.000000,120.000000,101.000000,84.700000,...,1.000000,1.00000,1.000000,1.000000,1.000000,6.000000,5.000000,72.000000,1.000000,3.00000

In [8]:
df['is_risky'] = df['abuse_type'].apply(lambda x: 0 if x == 'Legitimate' else 1)
df['is_risky'].value_counts()

is_risky
0    42060
1    17940
Name: count, dtype: int64

In [10]:
df.to_csv("returns_cleaned.csv", index=False)